version = 1

test_patterns = ["test/**"]

exclude_patterns = ["docs/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "airbnb"
  dialect = "typescript"