module.exports = {
  AC: { l: 'en' },
  AD: { l: 'ca' },
  AE: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  AF: { l: 'fa', c: 'persian', wd: [6, 0, 1, 2, 3, 4, 5], we: [4, 5] },
  AG: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  AI: { l: 'en' },
  AL: { l: 'sq' },
  AM: { l: 'hy' },
  AO: { l: 'pt' },
  AR: { l: 'es' },
  AS: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  AT: { l: 'de' },
  AU: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  AW: { l: 'nl' },
  AX: { l: 'sv' },
  AZ: { l: 'az' },
  BA: { l: 'bs' },
  BB: { l: 'en' },
  BD: { l: 'bn', wd: [0, 1, 2, 3, 4, 5, 6] },
  BE: { l: 'en' },
  BF: { l: 'fr' },
  BG: { l: 'bg' },
  BH: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  BI: { l: 'rn' },
  BJ: { l: 'fr' },
  BL: { l: 'fr' },
  BM: { l: 'en' },
  BN: { l: 'ms' },
  BO: { l: 'es' },
  BQ: { l: 'nl' },
  BR: { l: 'pt', wd: [0, 1, 2, 3, 4, 5, 6] },
  BS: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  BT: { l: 'dz', wd: [0, 1, 2, 3, 4, 5, 6] },
  BW: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  BY: { l: 'be' },
  BZ: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  CA: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  CC: { l: 'en' },
  CD: { l: 'fr' },
  CF: { l: 'fr' },
  CG: { l: 'fr' },
  CH: { l: 'de' },
  CI: { l: 'fr' },
  CK: { l: 'en' },
  CL: { l: 'es' },
  CM: { l: 'fr' },
  CN: { l: 'zh', wd: [0, 1, 2, 3, 4, 5, 6] },
  CO: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  CR: { l: 'es' },
  CU: { l: 'es' },
  CV: { l: 'pt' },
  CW: { l: 'nl' },
  CX: { l: 'en' },
  CY: { l: 'el' },
  CZ: { l: 'cs' },
  DE: { l: 'de' },
  DG: { l: 'en' },
  DJ: { l: 'aa', wd: [6, 0, 1, 2, 3, 4, 5] },
  DK: { l: 'da' },
  DM: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  DO: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  DZ: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  EA: { l: 'es' },
  EC: { l: 'es' },
  EE: { l: 'et' },
  EG: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  EH: { l: 'ar' },
  ER: { l: 'ti' },
  ES: { l: 'es' },
  ET: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  FI: { l: 'fi' },
  FJ: { l: 'en' },
  FK: { l: 'en' },
  FM: { l: 'en' },
  FO: { l: 'fo' },
  FR: { l: 'fr' },
  GA: { l: 'fr' },
  GB: { l: 'en' },
  GD: { l: 'en' },
  GE: { l: 'ka' },
  GF: { l: 'fr' },
  GG: { l: 'en' },
  GH: { l: 'en' },
  GI: { l: 'en' },
  GL: { l: 'kl' },
  GM: { l: 'en' },
  GN: { l: 'fr' },
  GP: { l: 'fr' },
  GQ: { l: 'es' },
  GR: { l: 'el' },
  GT: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  GU: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  GW: { l: 'pt' },
  GY: { l: 'en' },
  HK: { l: 'zh', wd: [0, 1, 2, 3, 4, 5, 6] },
  HN: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  HR: { l: 'hr' },
  HT: { l: 'ht' },
  HU: { l: 'hu' },
  IC: { l: 'es' },
  ID: { l: 'id', wd: [0, 1, 2, 3, 4, 5, 6] },
  IE: { l: 'en' },
  IL: { l: 'he', wd: [0, 1, 2, 3, 4, 5, 6], we: [5, 6] },
  IM: { l: 'en' },
  IN: { l: 'hi', wd: [0, 1, 2, 3, 4, 5, 6], we: [0] },
  IO: { l: 'en' },
  IQ: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  IR: { l: 'fa', c: 'persian', wd: [6, 0, 1, 2, 3, 4, 5], we: [5] },
  IS: { l: 'is' },
  IT: { l: 'it' },
  JE: { l: 'en' },
  JM: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  JO: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  JP: { l: 'ja', wd: [0, 1, 2, 3, 4, 5, 6] },
  KE: { l: 'sw', wd: [0, 1, 2, 3, 4, 5, 6] },
  KG: { l: 'ky' },
  KH: { l: 'km', wd: [0, 1, 2, 3, 4, 5, 6] },
  KI: { l: 'en' },
  KM: { l: 'ar' },
  KN: { l: 'en' },
  KP: { l: 'ko' },
  KR: { l: 'ko', wd: [0, 1, 2, 3, 4, 5, 6] },
  KW: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  KY: { l: 'en' },
  KZ: { l: 'ru' },
  LA: { l: 'lo', wd: [0, 1, 2, 3, 4, 5, 6] },
  LB: { l: 'ar' },
  LC: { l: 'en' },
  LI: { l: 'de' },
  LK: { l: 'si' },
  LR: { l: 'en' },
  LS: { l: 'st' },
  LT: { l: 'lt' },
  LU: { l: 'fr' },
  LV: { l: 'lv' },
  LY: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  MA: { l: 'fr' },
  MC: { l: 'fr' },
  MD: { l: 'ro' },
  ME: { l: 'sq' },
  MF: { l: 'fr' },
  MG: { l: 'mg' },
  MH: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  MK: { l: 'mk' },
  ML: { l: 'bm' },
  MM: { l: 'my', wd: [0, 1, 2, 3, 4, 5, 6] },
  MN: { l: 'mn' },
  MO: { l: 'zh', wd: [0, 1, 2, 3, 4, 5, 6] },
  MP: { l: 'en' },
  MQ: { l: 'fr' },
  MR: { l: 'ar' },
  MS: { l: 'en' },
  MT: { l: 'mt', wd: [0, 1, 2, 3, 4, 5, 6] },
  MU: { l: 'en' },
  MV: { l: 'dv', wd: [5, 6, 0, 1, 2, 3, 4] },
  MW: { l: 'en' },
  MX: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  MY: { l: 'ms' },
  MZ: { l: 'pt', wd: [0, 1, 2, 3, 4, 5, 6] },
  NA: { l: 'af' },
  NC: { l: 'fr' },
  NE: { l: 'ha' },
  NF: { l: 'en' },
  NG: { l: 'en' },
  NI: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  NL: { l: 'nl' },
  NO: { l: 'nb' },
  NP: { l: 'ne', wd: [0, 1, 2, 3, 4, 5, 6] },
  NR: { l: 'en' },
  NU: { l: 'en' },
  NZ: { l: 'en' },
  OM: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  PA: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  PE: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  PF: { l: 'fr' },
  PG: { l: 'en' },
  PH: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  PK: { l: 'ur', wd: [0, 1, 2, 3, 4, 5, 6] },
  PL: { l: 'pl' },
  PM: { l: 'fr' },
  PN: { l: 'en' },
  PR: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  PS: { l: 'ar' },
  PT: { l: 'pt', wd: [0, 1, 2, 3, 4, 5, 6] },
  PW: { l: 'en' },
  PY: { l: 'gn', wd: [0, 1, 2, 3, 4, 5, 6] },
  QA: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  RE: { l: 'fr' },
  RO: { l: 'ro' },
  RS: { l: 'sr' },
  RU: { l: 'ru' },
  RW: { l: 'rw' },
  SA: { l: 'ar', c: 'islamicc', wd: [0, 1, 2, 3, 4, 5, 6], we: [5, 6] },
  SB: { l: 'en' },
  SC: { l: 'fr' },
  SD: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  SE: { l: 'sv' },
  SG: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  SH: { l: 'en' },
  SI: { l: 'sl' },
  SJ: { l: 'nb' },
  SK: { l: 'sk' },
  SL: { l: 'en' },
  SM: { l: 'it' },
  SN: { l: 'wo' },
  SO: { l: 'so' },
  SR: { l: 'nl' },
  SS: { l: 'ar' },
  ST: { l: 'pt' },
  SV: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  SX: { l: 'en' },
  SY: { l: 'ar', wd: [6, 0, 1, 2, 3, 4, 5], we: [5, 6] },
  SZ: { l: 'en' },
  TA: { l: 'en' },
  TC: { l: 'en' },
  TD: { l: 'fr' },
  TF: { l: 'fr' },
  TG: { l: 'fr' },
  TH: { l: 'th', c: 'buddhist', wd: [0, 1, 2, 3, 4, 5, 6] },
  TJ: { l: 'tg' },
  TK: { l: 'en' },
  TL: { l: 'pt' },
  TM: { l: 'tk' },
  TN: { l: 'ar' },
  TO: { l: 'to' },
  TR: { l: 'tr' },
  TT: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  TV: { l: 'en' },
  TW: { l: 'zh', wd: [0, 1, 2, 3, 4, 5, 6] },
  TZ: { l: 'sw' },
  UA: { l: 'ru' },
  UG: { l: 'sw', we: [0] },
  UM: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  US: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  UY: { l: 'es' },
  UZ: { l: 'uz' },
  VA: { l: 'it' },
  VC: { l: 'en' },
  VE: { l: 'es', wd: [0, 1, 2, 3, 4, 5, 6] },
  VG: { l: 'en' },
  VI: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  VN: { l: 'vi' },
  VU: { l: 'bi' },
  WF: { l: 'fr' },
  WS: { l: 'sm', wd: [0, 1, 2, 3, 4, 5, 6] },
  XK: { l: 'sq' },
  YE: { l: 'ar', wd: [0, 1, 2, 3, 4, 5, 6], we: [5, 6] },
  YT: { l: 'fr' },
  ZA: { l: 'en', wd: [0, 1, 2, 3, 4, 5, 6] },
  ZM: { l: 'en' },
  ZW: { l: 'sn', wd: [0, 1, 2, 3, 4, 5, 6] },
};
